USE [master]
GO

/****** Object:  Database [dbUniversity]    Script Date: 25/4/2022 3:28:01 a. m. ******/
CREATE DATABASE [dbUniversity] ON  PRIMARY 
( NAME = N'dbUniversity', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\dbUniversity.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbUniversity_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\dbUniversity_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbUniversity].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbUniversity] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbUniversity] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbUniversity] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbUniversity] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbUniversity] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbUniversity] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbUniversity] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbUniversity] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbUniversity] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbUniversity] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbUniversity] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbUniversity] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbUniversity] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbUniversity] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbUniversity] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbUniversity] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbUniversity] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbUniversity] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbUniversity] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbUniversity] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbUniversity] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbUniversity] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbUniversity] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbUniversity] SET  MULTI_USER 
GO

ALTER DATABASE [dbUniversity] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbUniversity] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbUniversity] SET  READ_WRITE 
GO

